### ISSUE TITLE
Event blocking in multiline textfield

### ISSUE THREAD

**Issue by Me1000** [luddep/LPKit#16]
With regard to: http://github.com/280north/issues/issues/#issue/30

The fix is the same for what we did to get selectable text in the CPTextField I believe… 
At least for the selection issue…

Scrolling on the other hand might be a little harder, I'll work on that sometime if you don't have a fix. :)

**Comment by luddep** [comment]
I have no idea how it was fixed in CPTextField.

Anyway, this really isn't a priority for me right now - but if anyone fixes it, I'll gladly merge it in.

**Comment by Me1000** [comment]
Alright, I'll take a look sometime, it basically comes down to cappuccino is blocking the events from reaching the browser… 

For reference: http://github.com/280north/cappuccino/commit/39ba9b9a4f98f7434e9b79cd8f77d31fefcacd17

**Comment by Me1000** [comment]
Fix here: http://github.com/Me1000/LPKit/commit/ec2eca802c7fd69122fe86c01eff8831f6e1c434

**Comment by luddep** [comment]
closed by 7814412daa86fbb2cf8e943b387356f69547ccfd
