### ISSUE TITLE
LPMultiLineTextField is missing support for right and center text alignment

### ISSUE THREAD

**Issue by BlairDuncan** [luddep/LPKit#18]
Fix is here,
http://gist.github.com/548887
(it just adds a switch case at the end of the layoutSubviews method.)

**Comment by BlairDuncan** [comment]
Commit is here
http://github.com/BlairDuncan/LPKit/commit/56ac21e0841155525775f4b3e5aa1b1388e6bf78

**Comment by luddep** [comment]
Looks good. Would you mind doing a pull request with this commit and adding support for CPJustifiedTextAlignment as well? Not sure if <textfield> supports it though, but if it does, it should be in there.

**Comment by BlairDuncan** [comment]
Unfortunately textarea does not support justified text.
Just left,right,center.
