### ISSUE TITLE
LPLocationController sends notification twice on init

### ISSUE THREAD

**Issue by nickjs** [luddep/LPKit#8]
Calling [[LPLocationController sharedLocationController] addObserver:selector:] as the first call to LPLocationController will result in the locationDidChange notification being sent twice. This is due to the fact that the initial value of the hash is not cached before the first timer fires, even though -addObserver:selector: will immediately fire with the hash value. The solution would be to simply cache the current hash value in -init.

**Comment by luddep** [comment]
fix for notification being sent twice on LPLocationController init. Closed by 6e9a2d375702db8be6f40dd27fd8fac41d8ed336
